# Generated by Django 2.2.6 on 2019-10-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191012_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='displayname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
