# Generated by Django 2.2.6 on 2019-10-12 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191012_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geofence',
            name='family',
        ),
        migrations.AddField(
            model_name='geofence',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geofence_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
